language: python
dist: focal
python:
  - "3.10"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential manpages-dev wget

# Install the required version of GLIBC
  - wget http://ftp.gnu.org/gnu/libc/glibc-2.36.tar.gz
  - tar -xvzf glibc-2.36.tar.gz
  - cd glibc-2.36
  - mkdir build
  - cd build
  - ../configure --prefix=$HOME/opt/glibc-2.36
  - make -j$(nproc)
  - make install
  - export LD_LIBRARY_PATH=$HOME/opt/glibc-2.36/lib:$LD_LIBRARY_PATH
  - cd ../..

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp

script:
  - chmod +x * && chmod +x RAGNAROK && ./RAGNAROK
