language: python
dist: focal  # Ubuntu 20.04
python:
  - "3.10"

before_install:
  - sudo apt-get update -qq  # Use quiet mode for faster output

install:
  - python3 -m pip install --quiet --upgrade pip
  - python3 -m pip install --quiet telebot pymongo aiohttp flask

script:
  - chmod +x RAGNAROK  # Make only the necessary file executable
  - python3 RAGNAROK.py
